# Generated by Django 4.1.4 on 2023-01-02 03:47

from django.db import migrations, models
import v1.phoneNumbers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('phoneNumber', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[v1.phoneNumbers.validators.validate_phone_number])),
                ('countryCode', models.CharField(max_length=2, null=True, validators=[v1.phoneNumbers.validators.validate_country_code])),
                ('areaCode', models.IntegerField(validators=[v1.phoneNumbers.validators.validate_area_code])),
                ('localPhoneNumber', models.IntegerField()),
            ],
        ),
    ]
